### ISSUE TITLE
Library does not export all ip2location properties to nginx module

### ISSUE THREAD

**Issue by Khez** [ip2location/ip2location-nginx#1]
Hello,

Currently the only properties exported are `country_code` and `country_name`

Judging by the code in [IP2Location.h](https://github.com/chrislim2888/IP2Location-C-Library/blob/master/libIP2Location/IP2Location.h), it wouldn't seem to hard to update the current module to export all of the underlying IP2LocationRecord properties.

Would you like a PR to fix this ?

Best Regards,
Khez

**Comment by ip2location-com** [comment]
It has been updated.
