### ISSUE TITLE
nginx config check not pass  

### ISSUE THREAD

**Issue by yuge994** [ip2location/ip2location-nginx#12]
my nginx binary file has been added module  
./configure --add-module=/usr/local/src/ip2location-nginx-master/
but when i use  "nginx -t " to check config   
i get this wrong 
root@test-nginx01:/usr/local/nginx/sbin# /usr/local/nginx/sbin/nginx -t 
nginx: [emerg] unknown directive "ip2location" in /usr/local/nginx/conf/nginx.conf:47
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed

/usr/local/nginx/conf/nginx.conf:47  is 
        ip2location on;
        ip2location_database /usr/local/nginx/conf/IP2LOCATION-LITE-DB1.BIN;
        ip2location_access_type shared_memory;

thx  :)

**Comment by yuge994** [comment]
but this conf is OK        
ip2location_database /usr/local/nginx/conf/IP2LOCATION-LITE-DB1.BIN;

**Comment by ip2location-com** [comment]
You no longer need to add the "ip2location" directive in the latest version.

Can I know where you see the documentation so I can update it?

**Comment by yuge994** [comment]
> You no longer need to add the "ip2location" directive in the latest version.
> 
> Can I know where you see the documentation so I can update it?

i read wrong  , the documentation is right
