### ISSUE TITLE
my nginx host cpu use time too high 

### ISSUE THREAD

**Issue by yuge994** [ip2location/ip2location-nginx#13]
when i use ip2location on nginx(add this config "ip2location_database /path/IP-COUNTRY-REGION-CITY.BIN;")  ,  my nginx host cpu use time will be too high after about 10 hours , and ip2location out of work too , how can i solve this problem 
thanks

**Comment by yuge994** [comment]
![image](https://user-images.githubusercontent.com/18188947/108966572-4c88e780-76b9-11eb-8b5c-f9523165ec92.png)
![image](https://user-images.githubusercontent.com/18188947/108966591-53175f00-76b9-11eb-89e9-0fbbf41deccc.png)

**Comment by yuge994** [comment]
when i want know what is nginx doing   
strace -p 12994 
i get unlimit this message 
lseek(57, 528384, SEEK_SET)             = 528384

**Comment by huangzx** [comment]
+1
same problem

**Comment by huangzx** [comment]
IP-COUNTRY.BIN works fine

**Comment by vshuraeff** [comment]
same issue when using `IPV6-{ANY}.BIN`. 
problem with high CPU usage appears when we use any BIN except `IP-COUNTRY.BIN`

**Comment by akomyagin** [comment]
+1
same problem

**Comment by Samehadar** [comment]
Hello there. We have the same problem..

**Comment by vpaull** [comment]
+1 same problem :(

**Comment by velikanov** [comment]
hi guys, we have the same exact issue firing in production
please pay attention @ip2location @Morganov

**Comment by ip2location-com** [comment]
We have tested with the latest Nginx v1.21.3 in Buster and so far no high cpu issue observed. Can you please let us know your setup in details as below? So that we can further retest for the issues.

* Nginx version
* IP2Location C Library version
* IP2Location Nginx version
* Linux distro and version
* Are you using static or dynamic module?
* Web framework used (if any), like Laravel, Django and so on.
* The average number of traffics to Nginx.

Thanks.

**Comment by mwcng** [comment]
Same issue here.

- Nginx 1.21.3
- IP2Location C Library 8.4.0 (latest)
- IP2Location Nginx Version (latest available)
- Ubuntu 20.04
- Static
- No Framework
- Around 1 million requests per hour

**I would like to point out that this only happens after reloading nginx. If I restart nginx instead of reloading there are 0 issues**. After reloading and waiting roughly 1-2 hours the cpu usage for a random nginx worker process shoots up to 100%

**Comment by vshuraeff** [comment]
we have almost same setup
dynamic module and latest nginx with ip2location C lib and sources from this repo
Symfony framework with serving static files, ubuntu 20.04, debian 9 and 10 
±500rps

**Comment by ip2location-com** [comment]
We had run numerous test based on the given environments, but still not manage to produce the errors. However, we do notice that the use of IP2LOCATION_SHARED_MEMORY is less friction to the CPU during the reload. Can you please try if it helps?

At line 433, please change to the below:
`IP2Location_open_mem(gcf->handler, IP2LOCATION_SHARED_MEMORY);`

Please re-compile the nginx and try again. Please let us know if any improvements found.

**Comment by andylipatov** [comment]
I definitely confirm the problem with nginx reload when IP2Location module is loaded. It doesn't depend on IP2LOCATION_SHARED_MEMORY or IP2LOCATION_CACHED_MEMORY. When module is not loaded config reload brings no problem, otherwize LoadAverage raises rapidly and Nginx processes start to utilize 100% CPU each. After 10-15 processes with 100% CPU utilization system seems to be quite slow and we have to stop/start nginx or switch to the other cluster node on frontend.At this moment some IP2Location headers send to backend are garbage ones like   'ip2l-city' contains '...f.\'..R.B.v.¼...t...Y.....\'....B1K......t...Y....[,..m.B*.......t...Y.....\'....B1K....', or  'ip2l-country-long' => ',....A3...', etc.
Tested on Debian 10 on 2xIntelCore 4116 Silver Xeons. 
Looking through the code of module I didn't find the correct closing code in case of reload and stopping nginx workers can't close and free their resources, and IP2Location module seems to use uninitialized or dirty memory while nginx is dying.

**Comment by ip2location-com** [comment]
Can you try to recompile with the latest [IP2Location-C library](https://github.com/chrislim2888/IP2Location-C-Library) and check if this issue is fixed?

**Comment by andylipatov** [comment]
We build the latest 2e915ce C-library and 710214c Nginx IP2Location module, no observed changes, the nginx process goes to 100% CPU throttling. It doesn't depend on version of Nginx 1.18.x-1.21.4 - all of them cann't reload in presence of IP2Location module. May be some cleanup should help the module to reload properly?

**Comment by hexasoft-my** [comment]
@andylipatov To narrow down the debugging process, may I know you are compiling as a static or dynamic module?

**Comment by huangzx** [comment]
> Can you try to recompile with the latest [IP2Location-C library](https://github.com/chrislim2888/IP2Location-C-Library) and check if this issue is fixed?

nothing changes, seems worse.

ubuntu 16.04
nginx 1.15.8 
ip2location-nginx         710214c31615f52759af78a4b884bff3cf5b4a78
IP2Location-C-Library  [2e915ce67a16734532d1a9f38f2e6341a049a879](https://github.com/chrislim2888/IP2Location-C-Library/commit/2e915ce67a16734532d1a9f38f2e6341a049a879)
compile as a static module
IPV6-COUNTRY.BIN

**Comment by andylipatov** [comment]
Dynamic one
/configure \
--with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-tBUzFN/nginx-1.21.4=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' \
--with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' \
--prefix=/usr/share/nginx \
--sbin-path=/usr/sbin \
--conf-path=/etc/nginx/nginx.conf \
--http-log-path=/var/log/nginx/access.log \
--error-log-path=/var/log/nginx/error.log \
--lock-path=/var/lock/nginx.lock \
--pid-path=/run/nginx.pid \
--modules-path=/usr/lib/nginx/modules \
--http-client-body-temp-path=/var/lib/nginx/body \
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
--http-proxy-temp-path=/var/lib/nginx/proxy \
--http-scgi-temp-path=/var/lib/nginx/scgi \
--http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
--with-debug \
--with-pcre-jit \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_realip_module \
--with-http_auth_request_module \
--with-http_v2_module \
--with-http_dav_module \
--with-http_slice_module \
--with-threads \
--with-http_addition_module \
--with-http_geoip_module=dynamic \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_image_filter_module=dynamic \
--with-http_sub_module \
--with-http_xslt_module=dynamic \
--with-stream=dynamic \
--with-stream_ssl_module \
--with-stream_ssl_preread_module \
--with-mail=dynamic \
--with-mail_ssl_module \
--add-module=/usr/src/nginx-module-vts \
--add-dynamic-module=/usr/src/ip2location-nginx-master

**Comment by vshuraeff** [comment]
after `nginx -s reload` we have two `nginx master` processes, one old and one new. old process can't stop

**Comment by everanium** [comment]
+1 But in my case i have very loaded nginx and see falling workers to 100% sys cpu usage by random nginx workers
not only after nginx reload, but during work too.

In all cases worker fall to 100% sys cpu usage.
I have two modules compiled with nginx - ip2location and ip2proxy together.

This is with cache memory:

lseek too with 100% system cpu usage by nginx workers.
```
lseek(261, 3490838696, SEEK_SET) = 3490838696
lseek(261, 3490838696, SEEK_SET) = 3490838696
lseek(261, 3490838696, SEEK_SET) = 3490838696
lseek(261, 3490838696, SEEK_SET) = 3490838696
lseek(261, 3490838696, SEEK_SET) = 3490838696
lseek(261, 3490838696, SEEK_SET) = 3490838696
lseek(261, 3490838696, SEEK_SET) = 3490838696
lseek(261, 3490838696, SEEK_SET) = 3490838696
lseek(261, 3490838696, SEEK_SET) = 3490838696
```
This is with shared memory:

Now strace on any 100% cpu nginx workers shows other result, not a simple loop with single SEEK_SET:

```
read(263, "", 4096) = 0
lseek(263, 3728, SEEK_CUR) = 1056400
read(263, "", 4096) = 0
lseek(263, 2249146368, SEEK_SET) = 2249146368
read(263, "", 3740) = 0
lseek(263, 3740, SEEK_CUR) = 3853258072
read(263, "\4\205\0\1\312\367\240\5\227\365\240\5\5\205\0\1\304\367\240\5\320\350\240\5\t\205\0\1\312\367\240\5"..., 4096) = 4096
lseek(263, 531161088, SEEK_SET) = 531161088
read(263, "\4\205\0\1\312\367\240\5\227\365\240\5\5\205\0\1\304\367\240\5\320\350\240\5\t\205\0\1\312\367\240\5"..., 4096) = 4096
lseek(263, 531165184, SEEK_SET) = 531165184
lseek(263, 3967135744, SEEK_SET) = 3967135744
read(263, "", 4096) = 0
lseek(263, 1268, SEEK_CUR) = 1053940
read(263, "", 4096) = 0
lseek(263, 3967135744, SEEK_SET) = 3967135744
read(263, "\4\205\0\1\312\367\240\5\227\365\240\5\5\205\0\1\304\367\240\5\320\350\240\5\t\205\0\1\312\367\240\5"..., 1280) = 1280
read(263, "\304\367\240\5\320\350\240\5\331\207\0\1\312\367\240\5\227\365\240\5\332\207\0\1\304\367\240\5\320\350\240\5"..., 4096) = 4096
lseek(263, 1390153728, SEEK_SET) = 1390153728
read(263, "", 4096) = 0
lseek(263, 2912, SEEK_CUR) = 1055584
read(263, "\304\367\240\5\320\350\240\5\331\207\0\1\312\367\240\5\227\365\240\5\332\207\0\1\304\367\240\5\320\350\240\5"..., 4096) = 4096
lseek(263, 1390153728, SEEK_SET) = 1390153728
read(263, "", 4096) = 0
lseek(263, 2924, SEEK_CUR) = 1055596
read(263, "", 4096) = 0
lseek(263, 2249146368, SEEK_SET) = 2249146368
read(263, "\4\205\0\1\312\367\240\5\227\365\240\5\5\205\0\1\304\367\240\5\320\350\240\5\t\205\0\1\312\367\240\5"..., 3728) = 3728
read(263, "\4\205\0\1\312\367\240\5\227\365\240\5\5\205\0\1\304\367\240\5\320\350\240\5\t\205\0\1\312\367\240\5"..., 4096) = 4096
lseek(263, 2249154192, SEEK_SET) = 2249154192
lseek(263, 531161088, SEEK_SET) = 531161088
read(263, "", 4096) = 0
lseek(263, 2088, SEEK_CUR) = 1054760
read(263, "\304\367\240\5\320\350\240\5\331\207\0\1\312\367\240\5\227\365\240\5\332\207\0\1\304\367\240\5\320\350\240\5"..., 4096) = 4096
lseek(263, 531161088, SEEK_SET) = 531161088
```

**Comment by pingvinton** [comment]
+1 We have the same problem. Random count of workers is using about 100% CPU:
Ubuntu 20.04
Linux Kernek 5.13.0-27-generic
Arch x86_64
nginx/1.20.2
Nginx php-fpm + Symfony framework
We are using two paid db IP2PROXY-IP-PROXYTYPE-COUNTRY.BIN and IPV6-COUNTRY.BIN with dynamically modules:
ngx_http_ip2location_module.so
ngx_http_ip2proxy_module.so


Issue:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/68642472/194780773-7d331e52-47f4-43a5-a818-f5397d472390.png">

When I do strace
I get unlimit this message:
lseek(519, 1380352, SEEK_SET)           = 1380352
lseek(519, 1380352, SEEK_SET)           = 1380352

**Comment by vshuraeff** [comment]
I recommend to switch to another geoip systems where is no such problems or they solves sometimes, but not this complete silence after 2 years of research

**Comment by ip2location-com** [comment]
Kindly try it again with the latest version.
