### ISSUE TITLE
in rare cases ip2location_country_short is empty

### ISSUE THREAD

**Issue by frankyhun** [ip2location/ip2location-nginx#14]
In rare cases ip2location_country_short variable is empty. In the nginx logs i see for the same IP the right country code, also before and after the request where it is empty.

**Comment by ip2location-com** [comment]
Do you have detailed instructions on how to reproduce this issue?

It will be helpful if you are able to provide your OS version, Nginx version, IP2Location BIN database size and date, IP address for further investigation.

**Comment by ip2location-com** [comment]
Kindly try it again with the latest version.

**Comment by rpv-tomsk** [comment]
Came here to find solution for the same issue.
Just compiled and installed latest module version. 
Will inform you if that NOT helps.

Thanks for your work.
