### ISSUE TITLE
Proxy, VPN, TOR detection

### ISSUE THREAD

**Issue by Media182** [ip2location/ip2location-nginx#17]
Is it possible to use this module with PX2BIN database to detect Proxy, VPN, TOR status for IP? Any special varaible for this?

**Comment by ip2location-com** [comment]
Yes, please use the $ip2proxy_proxy_type variable. This field will show the proxy type which includes TOR, WEB, SES, PUB, VPN, and DCH.

**Comment by Media182** [comment]
Just problem with loading PROXY DB when starting nginx:
[emerg] Unable to open database file "/usr/local/nginx/IP2PROXY-IP-PROXYTYPE-COUNTRY.BIN".
Incorrect IP2Location BIN file format. Please make sure that you are using the latest IP2Location BIN file.

**Comment by ip2location-com** [comment]
You are using the wrong module. Please use [IP2Proxy](https://github.com/ip2location/ip2proxy-nginx) module.
