### ISSUE TITLE
Can not load database file on nginx reload

### ISSUE THREAD

**Issue by markitosgv** [ip2location/ip2location-nginx#6]
Hi,

When I'm trying to do a nginx reload, I've got in error logs this

[emerg] can not load database file /root/ip2locationdb/A8F5F167F44F4964E6C998DEE827110C.bin using "shared_memory" access type in /etc/nginx/conf.d/ip2location.conf:2

If I do a nginx restart, everything goes ok. What's wrong with this?

**Comment by ip2location-com** [comment]
Hi,  please make sure that:

1. The .bin file is not corrupted. Download again and decompress it to test.
2. The file permission of .bin file is readable by Nginx.
3. Your system has sufficient memory to load the whole database.
