### ISSUE TITLE
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lip2location

### ISSUE THREAD

**Issue by arashkarami** [ip2location/ip2location-nginx#7]
we received an error after building nginx:

/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lip2location

can help me?

**Comment by ip2location-com** [comment]
Please make sure you had built and installed the IP2Location C library before you create the Nginx library.
