### ISSUE TITLE
can not load database file on service reload

### ISSUE THREAD

**Issue by zi0r** [ip2location/ip2location-nginx#8]
`2019/09/11 08:49:21 [emerg] 53086#102353: can not load database file /var/db/ip2location/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE.BIN using "shared_memory" access type in /usr/local/etc/nginx/nginx.conf:65`

This appears to be related to having more than 1 nginx worker.  As mentioned in #6 and #5.  The same issue exists with the ip2proxy nginx module.

If you reload a second time, the error does not recur.

Additional details:

1. The .bin file is not corrupted (it loads cleanly with a restart and via the perl module).
2. Permissions are fine (global readable).
3. Available memory is not an issue.

**Comment by zi0r** [comment]
After I see this error message, any subsequent reloads appear to cause the memory usage of the nginx process to increase by about the size of the ip2proxy+ip2location databases.

My suspicion is that in a multi-worker environment, we do not properly close/reload the database and free up the old memory.  I'm still investigating.

**Comment by ip2location-com** [comment]
Please compile with the latest version. The error should be gone now.
